server:
    port:
        10000
spring:
    application:
        name: oauth2-jwt-server
    datasource:
        username: root
        password: 123456
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.174.129:3306/bugstack_ddd
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
        database: mysql
    redis:
        host: 192.168.174.129